### ISSUE TITLE
Copy button

### ISSUE THREAD

**Issue by vpukhanov** [DraStudio/url-generator#1]
Hello, DraStudio. Thanks for creating such a useful page. I have a suggestion. What about adding the "Copy to Clipboard" button, which shows up when all required fields are completed. Maybe, using this [ZeroClipboard lib](https://github.com/zeroclipboard/ZeroClipboard) for this.
<br/>
Cheers,
paththeir

**Comment by DraStudio** [comment]
I like the idea; I just wish there was a cleaner solution than ZeroClipboard. It is the best I've found so far, but it does seem like overkill for such a simple task.

**Comment by vpukhanov** [comment]
Yep, I agree to you. I was searching for a simpler solution either. Everything stops on browsers' restrictions.
